specVersion: 0.2.0
name: fearless-acala
version: 1.0.0
description: Fearless SubQuery project
repository: https://github.com/soramitsu/fearless-subquery
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c'
  endpoint: wss://acala-polkadot.api.onfinality.io/public-ws
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleTransferKeepAlive
          kind: substrate/EventHandler
          filter:
            module: balances
            method: transfer_keep_alive
