specVersion: 0.2.0
name: fearless-kintsugi
version: 1.0.0
description: Fearless SubQuery project
repository: https://github.com/soramitsu/fearless-subquery
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x9af9a64e6e4da8e3073901c3ff0cc4c3aad9563786d89daf6ad820b6e14a0b8b'
  endpoint: wss://api-kusama.interlay.io/parachain
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 22000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleTokenTransfer
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: Transfer
