specVersion: 0.0.1
description: Fearless SubQuery project
repository: 'https://github.com/soramitsu/fearless-subquery'
schema: ./schema.graphql
network:
  endpoint: wss://kusama.rpc.robonomics.network/#
  types: {
                "Record": "Vec<u8>",
                "Technics": "Vec<u8>",
                "Economics": "{}",
                "Report": {
                    "index": "LiabilityIndex",
                    "sender": "AccountId",
                    "payload": "Vec<u8>",
                    "signature": "MultiSignature"
                },
                "ReportFor": "Report",
                "Agreement": {
                    "technics": "Technics",
                    "economics": "Economics",
                    "promisee": "AccountId",
                    "promisor": "AccountId",
                    "promisee_signature": "MultiSignature",
                    "promisor_signature": "MultiSignature"
                },
                "LiabilityIndex": "u32"
            }
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1

    # polkadot test slash bloks: 3570179

    # westend test stake block: 6000000
    # kusama test stake block: 8124580
    # polkadot test stake block: 5645004

    # polkadot test rewards block: 5704983
    mapping:
      handlers:
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleTransferKeepAlive
          kind: substrate/EventHandler
          filter:
            module: balances
            method: transfer_keep_alive
