specVersion: 1.0.0
name: Fearless-oak
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: 1.17.1
  query:
    name: '@subql/query'
    version: 1.10.1
description: Fearless SubQuery project
repository: 'https://github.com/soramitsu/fearless-subquery'
schema:
  file: ./schema.graphql
network:
  chainId: '0x0f62b701fb12d02237a33b84818c11f621653d2b1614c777973babf4652b535d'
  endpoint: 'wss://rpc.turing.oak.tech'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleTransferKeepAlive
          kind: substrate/EventHandler
          filter:
            module: balances
            method: transfer_keep_alive