specVersion: 0.2.0
name: fearless
version: 1.0.0
description: Fearless SubQuery project
repository: https://github.com/soramitsu/fearless-subquery
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d'
  endpoint: wss://wss.api.moonbeam.network
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 500000
    mapping:
      file: ./dist/index.js
      handlers:
        # Transfers
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleTransferKeepAlive
          kind: substrate/EventHandler
          filter:
            module: balances
            method: transfer_keep_alive
        # Delegation
        ## Stake
        - handler: stakingEventsHandler
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: Delegation
        - handler: stakingEventsHandler
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: DelegationIncreased
        ## Unstake
        - handler: stakingEventsHandler
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: DelegationDecreased
        - handler: stakingEventsHandler
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: DelegationRevoked
        ## Rewards
        - handler: stakingEventsHandler
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: Rewarded
        # Common
        # - handler: blockHandler
        #   kind: substrate/BlockHandler
