specVersion: 1.0.0
name: Fearless-Integritee
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: 1.17.1
  query:
    name: '@subql/query'
    version: 1.10.1
description: Fearless SubQuery project
repository: 'https://github.com/soramitsu/fearless-subquery'
schema:
  file: ./schema.graphql
network:
  chainId: '0xcdedc8eadbfa209d3f207bba541e57c3c58a667b05a2e1d1e86353c9000758da'
  endpoint: wss://api.solo.integritee.io
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleTransferKeepAlive
          kind: substrate/EventHandler
          filter:
            module: balances
            method: transfer_keep_alive