specVersion: 1.0.0
name: fearless-wallet-moonbeam
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: 1.2.1
  query:
    name: '@subql/query'
    version: 1.2.0
description: Fearless SubQuery project
repository: 'https://github.com/soramitsu/fearless-subquery'
schema:
  file: ./schema.graphql
network:
  chainId: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b'
  endpoint: 'wss://moonriver.api.onfinality.io/ws?apikey=70d75730-8f86-4ea4-924e-28579479531f'
  chaintypes:
    file: ./dist/chaintypes.js
  dictionary: https://api.subquery.network/sq/subquery/moonriver-dictionary
dataSources:
  - kind: substrate/Runtime
    startBlock: 2000000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: stakingEventsHandler
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: Delegation
        - handler: stakingEventsHandler
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: DelegationIncreased
        - handler: stakingEventsHandler
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: DelegationDecreased
        - handler: stakingEventsHandler
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: DelegationRevoked
        - handler: stakingEventsHandler
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: Rewarded
