specVersion: 1.0.0
name: fearless-subquery
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: 1.16.0
  query:
    name: '@subql/query'
    version: 1.9.1
description: 'Fearless-SubQuery-project'
repository: 'https://github.com/soramitsu/fearless-subquery'
schema:
  file: ./schema.graphql
network:
  chainId: '0xca93a37c913a25fa8fdb33c7f738afc39379cb71d37874a16d4c091a5aef9f89'
  endpoint: wss://imbue-kusama.imbue.network
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleTransferKeepAlive
          kind: substrate/EventHandler
          filter:
            module: balances
            method: transfer_keep_alive
