specVersion: 1.0.0
name: fearless
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: 1.4.1
  query:
    name: '@subql/query'
    version: 1.4.0
description: Fearless SubQuery project
repository: 'https://github.com/soramitsu/fearless-subquery'
schema:
  file: ./schema.graphql
network:
  chainId: '0x4ac80c99289841dd946ef92765bf659a307d39189b3ce374a92b5f0415ee17a1'
  endpoint: 'wss://ws.calamari.systems/'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleTransferKeepAlive
          kind: substrate/EventHandler
          filter:
            module: balances
            method: transfer_keep_alive
