
specVersion: 0.2.0
name: fearless-moonbase-alpha
version: 1.0.0
description: Fearless SubQuery project
repository: https://github.com/soramitsu/fearless-subquery
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527'
  endpoint: wss://moonbeam-alpha.api.onfinality.io/public-ws
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 2000000
    mapping:
      file: ./dist/index.js
      handlers:
        # Transfers
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleTransferKeepAlive
          kind: substrate/EventHandler
          filter:
            module: balances
            method: transfer_keep_alive
        # Delegation
        ## Stake
        - handler: stakingEventsHandler
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: Delegation
        - handler: stakingEventsHandler
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: DelegationIncreased
        ## Unstake
        - handler: stakingEventsHandler
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: DelegationDecreased
        - handler: stakingEventsHandler
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: DelegationRevoked
        ## Rewards
        - handler: stakingEventsHandler
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: Rewarded
        # Common
        # - handler: blockHandler
        #   kind: substrate/BlockHandler
